### ISSUE TITLE
Show optional media URL commented out

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/server-notifications-laravel#1]
Note that in the Ruby reference example, we demonstrate that an image URL can be used to send a message, but then we comment the line out so that the code works unchanged for numbers that don't support MMS:

https://www.twilio.com/docs/howto/walkthrough/server-notifications/ruby/rails#6

This tutorial should use the same technique. Accept an image URL as a parameter, but then comment out the line where you would actually send it.

I suggest using this helper method:

https://twilio-php.readthedocs.org/en/latest/usage/rest/messages.html#sending-a-message

**Comment by jsantos17** [comment]
I tried to follow the Ruby implementation by using `create`. Do you think a384fb29b1e81b774b7693dacbaffdc3957481aa addresses this issue?

**Comment by atbaker** [comment]
Going to close this since it's been a couple weeks and it looks like we're good here. @kwhinnery can open again if he still has concerns.
